version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: sleep 10s
workflows:
    build-and-test:
      jobs:
        - build-and-test